CREATE TABLE `addon_categories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`key` varchar(80) NOT NULL,
	`nameEn` varchar(160) NOT NULL,
	`nameEs` varchar(160) NOT NULL,
	`descriptionEn` text,
	`descriptionEs` text,
	`noteEn` text,
	`noteEs` text,
	`sortOrder` int NOT NULL DEFAULT 0,
	`isEnabled` boolean NOT NULL DEFAULT true,
	`showPublicHeading` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `addon_categories_id` PRIMARY KEY(`id`),
	CONSTRAINT `addon_categories_key_unique` UNIQUE(`key`)
);
--> statement-breakpoint
CREATE TABLE `addons` (
	`id` int AUTO_INCREMENT NOT NULL,
	`categoryId` int,
	`key` varchar(100) NOT NULL,
	`nameEn` varchar(180) NOT NULL,
	`nameEs` varchar(180) NOT NULL,
	`descriptionEn` text,
	`descriptionEs` text,
	`includedItemsEn` text,
	`includedItemsEs` text,
	`noteEn` text,
	`noteEs` text,
	`priceMode` enum('fixed','starting_at','custom_quote') NOT NULL DEFAULT 'fixed',
	`startingPriceCents` int NOT NULL,
	`mayVary` boolean NOT NULL DEFAULT false,
	`sortOrder` int NOT NULL DEFAULT 0,
	`isEnabled` boolean NOT NULL DEFAULT true,
	`archivedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `addons_id` PRIMARY KEY(`id`),
	CONSTRAINT `addons_key_unique` UNIQUE(`key`)
);
--> statement-breakpoint
CREATE TABLE `booking_addons` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bookingId` int NOT NULL,
	`addonId` int,
	`addonKey` varchar(100) NOT NULL,
	`categoryKey` varchar(80),
	`categoryNameEn` varchar(160),
	`categoryNameEs` varchar(160),
	`nameEn` varchar(180) NOT NULL,
	`nameEs` varchar(180) NOT NULL,
	`descriptionEn` text,
	`descriptionEs` text,
	`noteEn` text,
	`noteEs` text,
	`priceMode` enum('fixed','starting_at','custom_quote') NOT NULL DEFAULT 'fixed',
	`bookedPriceCents` int NOT NULL,
	`mayVary` boolean NOT NULL DEFAULT false,
	`quantity` int NOT NULL DEFAULT 1,
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `booking_addons_id` PRIMARY KEY(`id`),
	CONSTRAINT `booking_addons_booking_key_unique` UNIQUE(`bookingId`,`addonKey`)
);
